server:
  port: 8088
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/project
    username: user
    password: 123
    driver-class-name: org.postgresql.Driver

#  security:
#    user:
#      name: user
#      password: 123

  flyway:
    url: jdbc:postgresql://localhost:5432/project
    locations: classpath:db/version
    user: user
    password: 123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


#
#    application:
#      security:
#        jwt:
#          secret-key: 5A7134743777217A25432A462D4A614E635266556A586E3272357538782F413F
#          expiration: 86400000 # a day
#          refresh-token:
#            expiration: 604800000 # 7 days